version: '3.7'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3608:3608
    volumes:
      - .:/app
    command: npm dev